USE energy_monitoring;

-- Insert Energy Categories, these are never changed
INSERT INTO EnergyCategory (CategoryName, IsRenewable)
VALUES
('Renewable', 1),
('Non-Renewable', 0);

-- Insert renewable Energy Sources, these are constant too
INSERT INTO EnergySource (SourceName, CategoryID)
VALUES
('Solar', 1),
('Wind', 1),
('Hydro', 1),
('Geothermal', 1),
('Biomass', 1);

-- Insert non-renewable Energy Sources, also constant
INSERT INTO EnergySource (SourceName, CategoryID)
VALUES
('Natural Gas', 2),
('Coal', 2),
('Oil', 2),
('Nuclear', 2),
('Diesel', 2);

-- Insert regions
INSERT INTO Region (RegionName)
VALUES
('England'),
('Scotland'),
('Wales'),
('Northern Ireland');

-- GenerationRecord — The national generation via the source
-- SourceIDs: Solar=1, Wind=2, Hydro=3, Geothermal=4, Biomass=5
-- Natural Gas=6, Coal=7, Oil=8, Nuclear=9, Diesel=10
INSERT INTO GenerationRecord (SourceID, Year, Generation_GWh)
VALUES
-- 2022
(1, 2022, 13045.00),   -- Solar
(2, 2022, 79194.00),   -- Wind 
(3, 2022, 5695.00),    -- Hydro
(4, 2022, 0.00),       -- Geothermal 
(5, 2022, 33077.00),   -- Biomass
(6, 2022, 99101.00),   -- Natural Gas
(7, 2022, 1463.00),    -- Coal
(8, 2022, 2100.00),    -- Oil
(9, 2022, 65469.00),   -- Nuclear
(10, 2022, 500.00),    -- Diesel
-- 2023 
(1, 2023, 13900.00),   -- Solar 
(2, 2023, 82300.00),   -- Wind 
(3, 2023, 5750.00),    -- Hydro
(4, 2023, 0.00),       -- Geothermal
(5, 2023, 33800.00),   -- Biomass
(6, 2023, 97200.00),   -- Natural Gas
(7, 2023, 1800.00),    -- Coal
(8, 2023, 1900.00),    -- Oil
(9, 2023, 40600.00),   -- Nuclear 
(10, 2023, 400.00),    -- Diesel
-- 2024
(1, 2024, 14400.00),   -- Solar 
(2, 2024, 83300.00),   -- Wind 
(3, 2024, 5800.00),    -- Hydro
(4, 2024, 0.00),       -- Geothermal
(5, 2024, 40600.00),   -- Biomass 
(6, 2024, 84200.00),   -- Natural Gas 
(7, 2024, 1600.00),    -- Coal 
(8, 2024, 1700.00),    -- Oil
(9, 2024, 40600.00),   -- Nuclear 
(10, 2024, 300.00);    -- Diesel

-- RegionalGenerationRecord — The energy generated by region
-- RegionIDs: England=1, Scotland=2, Wales=3, Northern Ireland=4
INSERT INTO RegionalGenerationRecord (RegionID, SourceID, Year, Generation_GWh)
VALUES
-- England 2023
(1, 1, 2023, 11200.00),  -- Solar 
(1, 2, 2023, 32000.00),  -- Wind
(1, 6, 2023, 78000.00),  -- Natural Gas
(1, 9, 2023, 27000.00),  -- Nuclear
(1, 5, 2023, 22000.00),  -- Biomass 
-- Scotland 2023
(2, 2, 2023, 41000.00),  -- Wind 
(2, 3, 2023, 4800.00),   -- Hydro
(2, 9, 2023, 13600.00),  -- Nuclear 
-- Wales 2023
(3, 2, 2023, 7000.00),   -- Wind
(3, 5, 2023, 5000.00),   -- Biomass
-- Northern Ireland 2023
(4, 2, 2023, 2300.00),   -- Wind 
(4, 1, 2023, 350.00),    -- Solar
-- England 2024
(1, 1, 2024, 11600.00),
(1, 2, 2024, 33000.00),
(1, 6, 2024, 68000.00),  -- Gas 
(1, 9, 2024, 27000.00),
(1, 5, 2024, 28000.00),  -- Biomass 
-- Scotland 2024
(2, 2, 2024, 41500.00),
(2, 3, 2024, 5000.00),
(2, 9, 2024, 13600.00),
-- Wales 2024
(3, 2, 2024, 7200.00),
(3, 5, 2024, 6000.00),
-- Northern Ireland 2024
(4, 2, 2024, 1600.00),
(4, 1, 2024, 400.00);

-- AnnualEmissionsRecord — Yearly emissions 
INSERT INTO AnnualEmissionsRecord (Year, EMISSIONS_MtCO2e)
VALUES
(2019, 447.900),   -- pre-pandemic baseline
(2020, 405.500),   -- COVID drop
(2021, 427.300),   -- post-COVID rebound
(2022, 405.000),   -- final DESNZ figure
(2023, 384.200),   -- provisional DESNZ 
(2024, 371.000);   -- provisional DESNZ 

-- EnergyEmissionsTarget — The UKs target Energy Emissions
INSERT INTO EnergyEmissionsTarget (TargetYear, RenewableTarget_Pct, EmissionsTarget_MtCO2e)
VALUES
(2030, 95.00, 250.000),  -- Clean Power 2030: 95% clean generation target
(2035, 98.00, 180.000),  -- interim net zero pathway
(2040, 99.00, 110.000),  -- interim net zero pathway
(2050, 100.00, 0.000);   -- UK legally binding net zero target