-- Samuel Campbell SQL Reports

USE energy_monitoring;

-- 
-- Report 1: Dominant Energy Category Per Region
-- Report Title: Dominant Energy Category Per Region
-- Business Question: What is the most generated energy category in each UK region?
-- Why this report is useful: Identifies whether each UK region is primarily powered
--   by renewable or non-renewable sources, helping analysts
--   understand regional energy profiles and target areas
--   for investment in clean energy.
-- Tables used: RegionalGenerationRecord, Region, EnergySource, EnergyCategory
-- 

--a view is created here so this query can be reused across the system without rewriting it
CREATE VIEW vw_DominantCategoryPerRegion AS
SELECT
    r.RegionName,
    ec.CategoryName,
    --round is used to keep the output to 2 decimal places for readability
    ROUND(SUM(rgr.Generation_GWh), 2) AS TotalGeneration_GWh
FROM RegionalGenerationRecord rgr
--inner join region to get the region name instead of just the id
INNER JOIN Region r ON rgr.RegionID = r.RegionID
--inner join energysource to link generation records to their source
INNER JOIN EnergySource es ON rgr.SourceID = es.SourceID
--inner join energycategory to get the category name (renewable / non-renewable)
INNER JOIN EnergyCategory ec ON es.CategoryID = ec.CategoryID
--group by region and category so sum aggregates generation for each combination
GROUP BY r.RegionName, ec.CategoryName
--order by region first, then generation descending so the dominant category appears first per region
ORDER BY r.RegionName, TotalGeneration_GWh DESC;

--query the view to return all results
SELECT * FROM vw_DominantCategoryPerRegion;


-- 
-- Report 2: Energy Sources With Consistently Low National Generation
-- Report Title: Underperforming Energy Sources
-- Business Question: Which energy sources have never exceeded 10 GWh of total
--   generation across all recorded years?
-- Why this report is useful: Highlights minor or underutilised energy sources
--   in the UK national mix. This can help identify technologies
--   that may need more investment or policy support to grow.
-- Tables used: GenerationRecord, EnergySource, EnergyCategory
-- 

SELECT
    es.SourceName,
    ec.CategoryName,
    --isrenewable is a boolean stored as 1 or 0, included to show whether underperforming sources are renewable or not
    ec.IsRenewable,
    --count counts how many years of data exist for each source
    COUNT(gr.Year) AS YearsRecorded,
    ROUND(SUM(gr.Generation_GWh), 2) AS TotalGeneration_GWh,
    --avg shows the average generation per year, giving context alongside the total
    ROUND(AVG(gr.Generation_GWh), 2) AS AvgGenerationPerYear_GWh
FROM GenerationRecord gr
--inner join energysource to get the source name instead of just the id
INNER JOIN EnergySource es ON gr.SourceID = es.SourceID
--inner join energycategory to get the category and renewable flag
INNER JOIN EnergyCategory ec ON es.CategoryID = ec.CategoryID
--group by source so aggregate functions calculate per energy source
GROUP BY es.SourceName, ec.CategoryName, ec.IsRenewable
--having filters on the aggregated total, keeping only sources below the 10 gwh threshold
--where cannot be used here as it runs before aggregation, having runs after
HAVING TotalGeneration_GWh <= 10
--order by ascending so the lowest generating sources appear first
ORDER BY TotalGeneration_GWh ASC;


-- 
-- Report 3: Carbon Efficiency of UK Electricity Generation By Year
-- Report Title: Emissions Per GWh Generated By Year
-- Business Question: How carbon efficient is the UK's electricity generation,
--   and is it improving over time?
-- Why this report is useful: A falling emissions-per-GWh ratio shows the grid
--   is getting cleaner even if total generation stays the same.
--   This is a key indicator of progress towards net zero
--   that goes beyond just tracking raw emissions.
-- Tables used: AnnualEmissionsRecord, GenerationRecord
-- 

SELECT
    aer.Year,
    aer.EMISSIONS_MtCO2e AS ActualEmissions_MtCO2e,
    ROUND(SUM(gr.Generation_GWh), 2) AS TotalGeneration_GWh,
    ROUND(
        --nullif returns null if total generation is 0, preventing a divide by zero error
        --the result is multiplied by 1000 to convert from mtco2e per gwh to ktco2e per gwh
        aer.EMISSIONS_MtCO2e / NULLIF(SUM(gr.Generation_GWh), 0) * 1000,
    4) AS EmissionsPerGWh_ktCO2e
FROM AnnualEmissionsRecord aer
--left join is used instead of inner join so years with no generation records still appear in results
LEFT JOIN GenerationRecord gr ON aer.Year = gr.Year
--group by year and emissions so sum aggregates all generation records for each year
GROUP BY aer.Year, aer.EMISSIONS_MtCO2e
--order by year ascending to show the trend from earliest to most recent
ORDER BY aer.Year ASC;