-- Samuel Campbell SQL Reports

USE energy_monitoring;

-- =============================================
-- Report 1: Dominant Energy Category Per Region
-- Report Title: Dominant Energy Category Per Region
-- Business Question: What is the most generated energy category in each UK region?
-- Why this report is useful: Identifies whether each UK region is primarily powered
--   by renewable or non-renewable sources, helping analysts
--   understand regional energy profiles and target areas
--   for investment in clean energy.
-- Tables used: RegionalGenerationRecord, Region, EnergySource, EnergyCategory
-- =============================================

CREATE VIEW vw_DominantCategoryPerRegion AS
SELECT
    r.RegionName,
    ec.CategoryName,
    ROUND(SUM(rgr.Generation_GWh), 2) AS TotalGeneration_GWh
FROM RegionalGenerationRecord rgr
INNER JOIN Region r ON rgr.RegionID = r.RegionID
INNER JOIN EnergySource es ON rgr.SourceID = es.SourceID
INNER JOIN EnergyCategory ec ON es.CategoryID = ec.CategoryID
GROUP BY r.RegionName, ec.CategoryName
ORDER BY r.RegionName, TotalGeneration_GWh DESC;

SELECT * FROM vw_DominantCategoryPerRegion;


-- =============================================
-- Report 2: Energy Sources With Consistently Low National Generation
-- Report Title: Underperforming Energy Sources
-- Business Question: Which energy sources have never exceeded 10 GWh of total
--   generation across all recorded years?
-- Why this report is useful: Highlights minor or underutilised energy sources
--   in the UK national mix. This can help identify technologies
--   that may need more investment or policy support to grow.
-- Tables used: GenerationRecord, EnergySource, EnergyCategory
-- =============================================

SELECT
    es.SourceName,
    ec.CategoryName,
    ec.IsRenewable,
    COUNT(gr.Year) AS YearsRecorded,
    ROUND(SUM(gr.Generation_GWh), 2) AS TotalGeneration_GWh,
    ROUND(AVG(gr.Generation_GWh), 2) AS AvgGenerationPerYear_GWh
FROM GenerationRecord gr
INNER JOIN EnergySource es ON gr.SourceID = es.SourceID
INNER JOIN EnergyCategory ec ON es.CategoryID = ec.CategoryID
GROUP BY es.SourceName, ec.CategoryName, ec.IsRenewable
HAVING TotalGeneration_GWh <= 10
ORDER BY TotalGeneration_GWh ASC;


-- =============================================
-- Report 3: Carbon Efficiency of UK Electricity Generation By Year
-- Report Title: Emissions Per GWh Generated By Year
-- Business Question: How carbon efficient is the UK's electricity generation,
--   and is it improving over time?
-- Why this report is useful: A falling emissions-per-GWh ratio shows the grid
--   is getting cleaner even if total generation stays the same.
--   This is a key indicator of progress towards net zero
--   that goes beyond just tracking raw emissions.
-- Tables used: AnnualEmissionsRecord, GenerationRecord
-- =============================================

SELECT
    aer.Year,
    aer.EMISSIONS_MtCO2e AS ActualEmissions_MtCO2e,
    ROUND(SUM(gr.Generation_GWh), 2) AS TotalGeneration_GWh,
    ROUND(
        aer.EMISSIONS_MtCO2e / NULLIF(SUM(gr.Generation_GWh), 0) * 1000,
    4) AS EmissionsPerGWh_ktCO2e
FROM AnnualEmissionsRecord aer
LEFT JOIN GenerationRecord gr ON aer.Year = gr.Year
GROUP BY aer.Year, aer.EMISSIONS_MtCO2e
ORDER BY aer.Year ASC;