
-- check if database already exists and drop it, then create new database
DROP DATABASE IF EXISTS energy_monitoring;
CREATE DATABASE IF NOT EXISTS energy_monitoring;

-- check if tables exists, drop if they do. drop children first to prevent referential errors
DROP TABLE IF EXISTS GenerationRecord;
DROP TABLE IF EXISTS RegionalGenerationRecord;
DROP TABLE IF EXISTS EnergySource;
DROP TABLE IF EXISTS EnergyCategory;
DROP TABLE IF EXISTS Region;
DROP TABLE IF EXISTS AnnualEmissionsRecord;

-- create tables

-- table 1: energy category
-- this table stores 2 categories, renewable and non-renwable
-- a boolean value is assigned to represent whether the category is renewable or not
-- this is cleaner than simply having a boolean value in the energy source table as it supports normalisation
CREATE TABLE EnergyCategory(
    CategoryID INT AUTO_INCREMENT PRIMARY KEY,
    CategoryName VARCHAR(50) NOT NULL UNIQUE,
    IsRenewable BOOLEAN NOT NULL
);

-- table 2: energy source
-- this table stores a list of different energy sources, e.g. wind, solar, nuclear, gas, coal, etc.
-- references energy category to say whether a source is renewable or not
CREATE TABLE EnergySource(
    SourceID INT AUTO_INCREMENT PRIMARY KEY,
    SourceName VARCHAR(100) NOT NULL UNIQUE,
    CategoryID INT NOT NULL,
    FOREIGN KEY (CategoryID) REFERENCES EnergyCategory(CategoryID)
    ON DELETE CASCADE
);

-- table 3: region
-- this table simply stores a region within the UK, e.g. NI, England, Scotland, Wales
CREATE TABLE Region(
    RegionID INT AUTO_INCREMENT PRIMARY KEY,
    RegionName VARCHAR(50) NOT NULL UNIQUE
);

-- table 4: national generation record
-- this tables stores the total energy generated by one energy type for a specific year
CREATE TABLE GenerationRecord(
    GenerationID INT AUTO_INCREMENT PRIMARY KEY,
    SourceID INT NOT NULL,
    Year YEAR NOT NULL,
    Generation_GWh DECIMAL(12,2) NOT NULL CHECK (Generation_GWh>=0),
    UNIQUE (SourceID, Year),
    FOREIGN KEY (SourceID) REFERENCES EnergySource(SourceID)
);

-- table 5: regional generation record
-- this table is the same as GenerationRecord, but for a specific region in the UK
CREATE TABLE RegionalGenerationRecord(
    RegionalGenerationID INT AUTO_INCREMENT PRIMARY KEY,
    RegionID INT NOT NULL,
    SourceID INT NOT NULL,
    Year YEAR NOT NULL,
    Generation_GWh DECIMAL(12,2) NOT NULL CHECK (Generation_GWh>=0),
    UNIQUE (RegionID, SourceID, Year),
    FOREIGN KEY (RegionID) REFERENCES Region(RegionID),
    FOREIGN KEY (SourceID) REFERENCES EnergySource(SourceID)
);

-- table 6: annual emissions record
-- this table stores the annual co2 emissions for the entire UK
-- it uses the unit MtCO2e (Million Metric Tons of Carbon Dioxide Equivalent)
CREATE TABLE AnnualEmissionsRecord(
    Year YEAR PRIMARY KEY,
    EMISSIONS_MtCO2e DECIMAL(10,3) NOT NULL CHECK (EMISSIONS_MtCO2e >= 0)
);
-- );

-- Table 7: Energy Consumption table
-- This table tracks the energy consumption 
CREATE TABLE EnergyConsumptionRecord(
    ConsumptionID INT AUTO_INCREMENT PRIMARY KEY,
    RegionID INT NOT NULL,
    year Year NOT NULL
);